const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const state={user:null,departments:[],groups:[],users:[],tasks:[],taskHistory:[],cases:[],missingReports:[],snapshots:[],settings:{},editingReportId:'',editingReportData:null};
const ROLES=['employee','group_leader','director','minister','admin'];
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function roleText(r){return {employee:'员工',group_leader:'组长',director:'主任',minister:'部长',admin:'管理员'}[r]||r||''}
function currentReportDate(){const now=new Date(),pad=n=>String(n).padStart(2,'0');return `${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`}
function formatTimestamp(value){return String(value||'').replace('T',' ')}
function riskText(r){return {high:'高风险',medium:'中风险',low:'低风险',normal:'正常',unknown:'未知'}[r]||r||''}
function checkerText(id){return {report_duplicate_check:'日报查重',quality_check:'日报质量',testcase_check:'测试用例核验',code_check:'代码记录',document_check:'文档记录'}[id]||id}
function canManage(){return ['group_leader','director','minister'].includes(state.user?.role)}
function isBusiness(){return ['employee','group_leader','director','minister'].includes(state.user?.role)}
function isAdmin(){return state.user?.role==='admin'}
async function requestJson(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'请求失败');return d}
async function requestForm(url,form,method='POST'){const r=await fetch(url,{method,body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d}
async function downloadFile(url,name){const r=await fetch(url);if(!r.ok)throw new Error('下载失败');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function canAccessPanel(id){
  if(!state.user)return false;
  if(id==='admin')return isAdmin();
  if(['manager','taskHistory','snapshots'].includes(id))return canManage();
  return ['employee','myReports','periodicReports'].includes(id)&&isBusiness();
}
function defaultPanel(){return isAdmin()?'admin':'employee'}
function switchPanel(id){
  if(!canAccessPanel(id)||!document.getElementById(id))return false;
  $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.panel===id));
  $$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));
  window.scrollTo({top:0,behavior:'auto'});
  if(id==='taskHistory'&&canManage())refreshTaskHistory().catch(()=>{});
  return true;
}
function showAuthMode(m){$('#loginForm').classList.toggle('hidden',m!=='login');$('#registerForm').classList.toggle('hidden',m!=='register')}
function departmentOptions(current='',empty=true){return `${empty?'<option value="">选择部门</option>':''}${state.departments.map(d=>`<option value="${escapeHtml(d.department_id)}" ${d.department_id===current?'selected':''}>${escapeHtml(d.name)}</option>`).join('')}`}
function groupOptions(current='',departmentId='',empty=true){const rows=state.groups.filter(g=>!departmentId||g.department_id===departmentId);return `${empty?'<option value="">选择小组</option>':''}${rows.map(g=>`<option value="${escapeHtml(g.group_id)}" ${g.group_id===current?'selected':''}>${escapeHtml(g.name)}</option>`).join('')}`}
function roleOptions(current){return ROLES.map(r=>`<option value="${r}" ${r===current?'selected':''}>${roleText(r)}</option>`).join('')}
function renderReportRoleOptions(){const select=$('#reportRole');if(!select||!state.user)return;const directReportRole={group_leader:'employee',director:'group_leader',minister:'director'}[state.user.role]||'';select.innerHTML='<option value="">全部</option>'+(directReportRole?`<option value="${directReportRole}">仅${roleText(directReportRole)}</option>`:'');select.disabled=!directReportRole}
function applyRoleUi(){
  document.body.classList.toggle('authenticated',!!state.user);document.body.classList.toggle('is-business',isBusiness());document.body.classList.toggle('can-manage',canManage());document.body.classList.toggle('is-admin',isAdmin());document.body.classList.toggle('can-upload-snapshot',['group_leader','director'].includes(state.user?.role));
  if(!state.user)return;
  $('#statusPill').textContent=`${state.user.display_name||state.user.username} · ${roleText(state.user.role)}`;
  $('#orgChain').textContent=[state.user.department_name,state.user.group_name].filter(Boolean).join(' / ');
  if(isBusiness()){
    renderReportRoleOptions();
    const f=$('#reportForm');f.elements.name.value=state.user.display_name||'';f.elements.role_text.value=roleText(state.user.role);f.elements.department.value=state.user.department_name||'全公司';f.elements.group.value=state.user.group_name||'—';if(!state.editingReportId)f.elements.date.value=currentReportDate();
    const manager=f.elements.manager;manager.value=state.user.manager_display_name||(state.user.role==='minister'?'无（最高领导）':'');manager.readOnly=!!state.user.manager_display_name||state.user.role==='minister';manager.required=state.user.role!=='minister';
    renderDepartmentScopeOptions();
  }
  const activePanel=$('.panel.active')?.id;
  if(!canAccessPanel(activePanel))switchPanel(defaultPanel());
}
async function refreshAuth(){const data=await requestJson('/api/auth/me');state.user=data.user||null;await refreshPublicOrganisation();applyRoleUi();if(!state.user)return;if(isBusiness())await refreshMyReports();if(canManage())await Promise.all([refreshStatus(),refreshTasks(),refreshTaskHistory(),refreshResults(),refreshSnapshots()]);if(isAdmin())await refreshAdmin()}
async function refreshPublicOrganisation(){state.departments=await requestJson('/api/public/departments').catch(()=>[]);state.groups=await requestJson('/api/public/groups').catch(()=>[]);$('#registerDepartment').innerHTML=departmentOptions('',true);updateRegisterGroups()}
function updateRegisterGroups(){const did=$('#registerDepartment').value;$('#registerGroup').innerHTML=groupOptions('',did,true)}
function renderDepartmentScopeOptions(){const s=$('#departmentScope');if(!s||!state.user)return;if(['group_leader','director'].includes(state.user.role)){s.innerHTML=`<option value="${escapeHtml(state.user.department_id)}">${escapeHtml(state.user.department_name)}</option>`;s.disabled=true}else{s.innerHTML=`<option value="">全公司</option>${state.departments.map(d=>`<option value="${escapeHtml(d.department_id)}">${escapeHtml(d.name)}</option>`).join('')}`;s.disabled=false}}
function reportQuery(){return new URLSearchParams({name:$('#reportName').value.trim(),start:$('#reportStart').value,end:$('#reportEnd').value,role:$('#reportRole').value})}
async function refreshMyReports(){if(!isBusiness())return;const rows=await requestJson('/api/my/reports?'+reportQuery());$('#myReportList').innerHTML=rows.map(r=>`<tr><td>${escapeHtml(r.report_date)}</td><td>${escapeHtml(formatTimestamp(r.created_at))}${r.updated_at?`<br><span class="small-note">最后修改：${escapeHtml(formatTimestamp(r.updated_at))}</span>`:''}</td><td>${escapeHtml(r.employee_name)}</td><td><span class="role-pill">${roleText(r.submitter_role)}</span></td><td>${escapeHtml(r.department_name||'全公司')}<br><span class="small-note">${escapeHtml(r.group_name||'—')}</span></td><td>${escapeHtml(r.title_summary)}</td><td>已提交</td><td>${(r.artifacts||[]).map(a=>`<button class="secondary mini" data-artifact="${escapeHtml(a.artifact_id)}" data-file="${escapeHtml(a.original_filename)}">${escapeHtml(a.original_filename)}</button>`).join(' ')||'-'}</td><td><button class="secondary" data-download-report="${escapeHtml(r.report_id)}" data-file="${escapeHtml(r.original_filename)}">下载</button>${r.can_edit?` <button class="secondary" data-edit-report="${escapeHtml(r.report_id)}">更改</button>`:''}</td></tr>`).join('')||'<tr><td colspan="9">暂无日报记录</td></tr>'}
async function refreshStatus(){const s=await requestJson('/api/status');$('#inputCount').textContent=s.metadata?.report_count??'-';$('#resultCount').textContent=s.result_count??'-';$('#highRiskCount').textContent=s.high_risk_count??'-';$('#errorCount').textContent=s.error_count??'-'}
function taskName(t){return t.task_name||t.task_id}
function setCheckProgress(active,message=''){const status=$('#taskMessage');status.textContent=message;status.classList.toggle('loading',active);$('#runCheck').disabled=active;$('#taskForm').querySelector('button[type="submit"]').disabled=active}
function checkCompletionMessage(result,startedAt){const seconds=((Date.now()-startedAt)/1000).toFixed(1),summary=result.summary||{};return `查重完成，用时 ${seconds} 秒：日报 ${summary.report_count||0} 份，高风险 ${summary.high_risk_count||0} 份，缺报 ${summary.missing_report_count||0} 条。`}
function taskRows(tasks,{view=true}={}){return tasks.map(t=>`<tr><td>${escapeHtml(taskName(t))}</td><td>${escapeHtml(t.status)}${t.error_message?`<br><span class="small-note">${escapeHtml(t.error_message)}</span>`:''}</td><td>日报 ${t.summary?.report_count||0} / 高风险 ${t.summary?.high_risk_count||0} / 缺报 ${t.summary?.missing_report_count||0}</td><td>${escapeHtml(t.created_at)}</td><td><div class="task-actions">${view?`<button class="secondary" data-view-task="${escapeHtml(t.task_id)}" data-task-name="${escapeHtml(taskName(t))}">查看</button>`:''}<button class="secondary" data-xlsx-task="${escapeHtml(t.task_id)}">Excel</button><button class="secondary" data-missing-task="${escapeHtml(t.task_id)}">缺报名单</button><button class="secondary" data-docx-task="${escapeHtml(t.task_id)}">Word</button><button class="danger-button" data-delete-task="${escapeHtml(t.task_id)}">删除</button></div></td></tr>`).join('')||'<tr><td colspan="5">暂无任务</td></tr>'}
async function refreshTasks(){const q=new URLSearchParams({status:$('#taskStatus').value,start:$('#taskStart').value,end:$('#taskEnd').value});state.tasks=await requestJson('/api/tasks?'+q);$('#taskList').innerHTML=taskRows(state.tasks,{view:true})}
async function refreshTaskHistory(){state.taskHistory=await requestJson('/api/tasks?include_hidden=1');$('#taskHistoryList').innerHTML=taskRows(state.taskHistory,{view:false})}
async function refreshResults(taskId='',taskName=''){let selectedId=taskId;if(!selectedId){const tasks=await requestJson('/api/tasks');selectedId=tasks[0]?.task_id||'';taskName=tasks[0]?.task_name||selectedId}state.cases=selectedId?await requestJson(`/api/tasks/${encodeURIComponent(selectedId)}/results`):[];state.missingReports=selectedId?await requestJson(`/api/tasks/${encodeURIComponent(selectedId)}/missing-reports`):[];$('#selectedTaskLabel').textContent=selectedId?`任务 ${taskName||selectedId} 的结果`:'最近一次任务结果';renderResults();renderMissingReports()}
function renderResults(){const q=$('#searchBox').value.trim().toLowerCase(),risk=$('#riskFilter').value,date=$('#dateFilter').value;const rows=state.cases.filter(x=>(!date||x.report_date===date)&&(!risk||x.overall_risk===risk));const visible=rows.filter(x=>[x.employee_name,x.department_name,x.report_date,x.title_summary,JSON.stringify(x.checks||[])].join(' ').toLowerCase().includes(q));$('#reviewCaseList').innerHTML=visible.map(renderCase).join('')||'<div class="card">暂无结果</div>'}
function renderMissingReports(){const rows=state.missingReports||[];$('#missingReportLabel').textContent=`缺报人员（${rows.length} 条）`;$('#missingReportList').innerHTML=rows.map(r=>`<tr><td>${escapeHtml(r.report_date)}</td><td>${escapeHtml(r.employee_name)}</td><td>${escapeHtml(roleText(r.role))}</td><td>${escapeHtml(r.department_name||'—')} / ${escapeHtml(r.group_name||'—')}</td></tr>`).join('')||'<tr><td colspan="4">所选工作日内无缺报人员</td></tr>'}
function renderCase(c){return `<article class="case-card"><div class="case-head"><div><h2>${escapeHtml(c.employee_name||'未命名')}</h2><p>${escapeHtml(c.department_name||'')} · ${escapeHtml(c.report_date||'')}</p><p>${escapeHtml(c.title_summary||'')}</p></div><span class="badge ${escapeHtml(c.overall_risk)}">${riskText(c.overall_risk)}</span></div><div class="check-grid">${(c.checks||[]).filter(x=>x.triggered).map(renderCheck).join('')}</div></article>`}
function renderCheck(c){const fs=(c.findings||[]).map(f=>`<tr><td>${escapeHtml(f.target_name)}</td><td>${escapeHtml(f.matched_target_name||'')}</td><td>${Number(f.score||0).toFixed(2)}</td><td><span class="badge ${escapeHtml(f.risk_level)}">${riskText(f.risk_level)}</span></td><td>${escapeHtml(f.reason||'')}</td></tr>`).join('');return `<section class="check-card"><div class="check-head"><strong>${checkerText(c.checker_id)}</strong><span class="badge ${escapeHtml(c.risk_level)}">${riskText(c.risk_level)}</span></div><p>${escapeHtml(c.summary||'')}</p>${fs?`<div class="table-wrap compact"><table><thead><tr><th>当前对象</th><th>匹配对象</th><th>分值</th><th>风险</th><th>原因</th></tr></thead><tbody>${fs}</tbody></table></div>`:''}</section>`}
function rowHtml(fields){return `<tr>${fields.map(f=>`<td><input name="${f.name}" placeholder="${escapeHtml(f.placeholder||'')}" value="${escapeHtml(f.value||'')}" /></td>`).join('')}<td><button type="button" class="secondary remove-row">删除</button></td></tr>`}
function collectRows(sel){return $$(sel+' tr').map(r=>{const o={};r.querySelectorAll('input').forEach(i=>o[i.name]=i.value.trim());return o}).filter(o=>Object.values(o).some(Boolean))}
function resetReportForm(){state.editingReportId='';state.editingReportData=null;const form=$('#reportForm');form.reset();$('#codeBody').innerHTML='';$('#documentBody').innerHTML='';['#codeFiles','#documentFiles','#testcaseFiles'].forEach(s=>{const input=$(s);if(input)input.value=''});$('#submitReport').textContent='提交日报';$('#cancelReportEdit').classList.add('hidden');$('#formMessage').textContent='';applyRoleUi()}
async function startReportEdit(reportId){const report=await requestJson(`/api/my/reports/${encodeURIComponent(reportId)}`);state.editingReportId=reportId;state.editingReportData=report;const form=$('#reportForm');form.elements.name.value=report.employee_name||'';form.elements.role_text.value=roleText(report.submitter_role);form.elements.department.value=report.department_name||'全公司';form.elements.group.value=report.group_name||'—';form.elements.date.value=report.report_date||'';form.elements.manager.value=report.manager||'';form.elements.title_summary.value=report.title_summary||'';form.elements.work_description.value=report.work_description||'';$('#codeBody').innerHTML=(report.code_items||[]).map(item=>rowHtml([{name:'file_name',placeholder:'main.py',value:item.file_name},{name:'language',placeholder:'python',value:item.language},{name:'work_type',placeholder:'修改',value:item.work_type},{name:'description',placeholder:'说明',value:item.description}])).join('');$('#documentBody').innerHTML=(report.document_items||[]).map(item=>rowHtml([{name:'document_name',placeholder:'设计说明',value:item.document_name},{name:'document_type',placeholder:'docx',value:item.document_type},{name:'work_type',placeholder:'修改',value:item.work_type},{name:'description',placeholder:'说明',value:item.description}])).join('');$('#submitReport').textContent='保存更改';$('#cancelReportEdit').classList.remove('hidden');$('#formMessage').textContent=`正在更改 ${report.report_date} 的日报；已有附件会保留。`;switchPanel('employee');window.scrollTo({top:0,behavior:'smooth'})}
async function refreshSnapshots(){if(!canManage())return;state.snapshots=await requestJson('/api/testcase-snapshots');$('#snapshotList').innerHTML=state.snapshots.map(s=>`<tr><td>${escapeHtml(s.department_name||'')}</td><td>${escapeHtml(s.group_name||s.group_id||'')}</td><td>${escapeHtml(s.snapshot_date)}</td><td>${escapeHtml(s.original_filename)}</td><td>${escapeHtml(s.uploaded_at)}</td><td><button class="secondary" data-download-snapshot="${escapeHtml(s.snapshot_id)}" data-file="${escapeHtml(s.original_filename)}">下载</button></td></tr>`).join('')||'<tr><td colspan="6">暂无小组汇总表</td></tr>';renderSnapshotGroupOptions()}
function renderSnapshotGroupOptions(){
  const wrap=$('#snapshotGroupWrap'),select=$('#snapshotGroup');
  if(!wrap||!select||!state.user)return;
  if(state.user.role==='group_leader'){
    select.innerHTML=`<option value="${escapeHtml(state.user.group_id)}">${escapeHtml(state.user.group_name||state.user.group_id)}</option>`;
    select.disabled=true;select.required=false;
  }else if(state.user.role==='director'){
    select.innerHTML=groupOptions('',state.user.department_id,true);select.disabled=false;select.required=true;
  }else{
    select.innerHTML='<option value="">—</option>';select.disabled=true;select.required=false;
  }
}
async function refreshAdmin(){await refreshDepartments();await refreshGroups();await refreshUsers();await refreshSettings()}
function setAdminMessage(id,message=''){const el=$(id);if(el)el.textContent=message}
async function refreshOrganisationAdmin(){await refreshDepartments();await refreshGroups();await refreshUsers()}
function renderDepartments(){state.departments.sort((a,b)=>String(a.name).localeCompare(String(b.name),'zh-CN'));$('#departmentList').innerHTML=state.departments.map(d=>`<tr><td>${escapeHtml(d.department_id)}</td><td><input data-dept="${escapeHtml(d.department_id)}" data-field="name" value="${escapeHtml(d.name)}" /></td><td><input data-dept="${escapeHtml(d.department_id)}" data-field="parent_department_id" value="${escapeHtml(d.parent_department_id||'')}" /></td><td><input type="checkbox" data-dept="${escapeHtml(d.department_id)}" data-field="enabled" ${d.enabled?'checked':''}/></td><td><button type="button" class="secondary" data-save-dept="${escapeHtml(d.department_id)}">保存</button><button type="button" class="danger-button" data-delete-dept="${escapeHtml(d.department_id)}">删除</button></td></tr>`).join('');$('#userDepartment').innerHTML=departmentOptions('',true);$('#groupDepartment').innerHTML=departmentOptions('',true)}
function renderGroups(){state.groups.sort((a,b)=>`${a.department_name||''}${a.name}`.localeCompare(`${b.department_name||''}${b.name}`,'zh-CN'));$('#groupList').innerHTML=state.groups.map(g=>`<tr><td>${escapeHtml(g.group_id)}</td><td><select data-group="${escapeHtml(g.group_id)}" data-field="department_id">${departmentOptions(g.department_id,false)}</select></td><td><input data-group="${escapeHtml(g.group_id)}" data-field="name" value="${escapeHtml(g.name)}" /></td><td><input type="checkbox" data-group="${escapeHtml(g.group_id)}" data-field="enabled" ${g.enabled?'checked':''}/></td><td><button type="button" class="secondary" data-save-group="${escapeHtml(g.group_id)}">保存</button><button type="button" class="danger-button" data-delete-group="${escapeHtml(g.group_id)}">删除</button></td></tr>`).join('');updateAdminGroupOptions()}
async function refreshDepartments(){state.departments=await requestJson('/api/departments');renderDepartments()}
async function refreshGroups(){state.groups=await requestJson('/api/groups');renderGroups()}
function updateAdminGroupOptions(){const did=$('#userDepartment').value;$('#userGroup').innerHTML=groupOptions('',did,true)}
function applyUserFormRules(){const role=$('#userRole').value,department=$('#userDepartment'),group=$('#userGroup');const noDepartment=['minister','admin'].includes(role);department.disabled=noDepartment;department.required=!noDepartment;group.disabled=noDepartment||role==='director';group.required=['employee','group_leader'].includes(role);if(noDepartment)department.value='';if(group.disabled)group.value=''}
async function refreshUsers(){state.users=await requestJson('/api/users');$('#userList').innerHTML=state.users.map(u=>`<tr><td>${escapeHtml(u.username)}</td><td><input data-user="${escapeHtml(u.user_id)}" data-field="display_name" value="${escapeHtml(u.display_name)}" /></td><td><select data-user="${escapeHtml(u.user_id)}" data-field="role">${roleOptions(u.role)}</select></td><td><select data-user="${escapeHtml(u.user_id)}" data-field="department_id">${departmentOptions(u.department_id,true)}</select></td><td><select data-user="${escapeHtml(u.user_id)}" data-field="group_id">${groupOptions(u.group_id,u.department_id,true)}</select></td><td>${escapeHtml(u.manager_display_name||'—')}</td><td><input type="checkbox" data-user="${escapeHtml(u.user_id)}" data-field="enabled" ${u.enabled?'checked':''}/></td><td><button class="secondary" data-save-user="${escapeHtml(u.user_id)}">保存</button><button class="danger-button" data-delete-user="${escapeHtml(u.user_id)}">删除</button></td></tr>`).join('')}
async function refreshSettings(){state.settings=await requestJson('/api/admin/settings');$('#settingsForm').innerHTML=Object.entries(state.settings).map(([k,v])=>`<label><span>${escapeHtml(settingLabel(k))}</span><input name="${escapeHtml(k)}" value="${escapeHtml(v)}" /></label>`).join('')+'<button class="primary">保存参数</button>'}
function settingLabel(k){return {'daily_duplicate.llm_candidate_top_n':'大模型候选数 Top-N','daily_duplicate.llm_candidate_score_threshold':'候选最低分','daily_duplicate.low_info_candidate_score_threshold':'低信息候选分','daily_duplicate.max_candidates':'最大召回候选数','daily_duplicate.self_history_days':'本人历史天数','daily_duplicate.cross_user_days':'跨人近几天','daily_duplicate.cross_user_scope':'跨人范围','daily_duplicate.score_weights.text':'文本权重','daily_duplicate.score_weights.semantic':'语义权重','daily_duplicate.score_weights.recency':'时间权重','llm_judge.enabled':'启用大模型','llm_judge.base_url':'模型 Base URL','llm_judge.chat_path':'模型路径','llm_judge.model':'模型名','llm_judge.api_key_file':'API Key 文件路径','llm_judge.api_key_env':'API Key 环境变量（兼容）','testcase_verification.enabled':'启用测试用例核验','testcase_verification.self_history_days':'测试用例本人历史天数','testcase_verification.self_history_high_rate':'测试用例查重高风险阈值(0-1)','testcase_verification.self_history_medium_rate':'测试用例查重中风险阈值(0-1)','checks.enable_code_check':'启用代码记录检查','checks.enable_document_check':'启用文档记录检查','upload.max_file_mb':'上传大小 MB'}[k]||k}
function bindEvents(){
  $('#showRegister').onclick=()=>showAuthMode('register');$('#showLogin').onclick=()=>showAuthMode('login');$('#registerDepartment').onchange=updateRegisterGroups;
  $('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;$('#loginMessage').textContent='登录中...';try{await requestJson('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))});$('#loginMessage').textContent='';await refreshAuth()}catch(err){$('#loginMessage').textContent=err.message}};
  $('#registerForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;try{await requestJson('/api/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))});$('#registerMessage').textContent='注册成功，请登录';showAuthMode('login')}catch(err){$('#registerMessage').textContent=err.message}};
  $('#logoutButton').onclick=async()=>{await requestJson('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()};$$('.tab').forEach(t=>t.onclick=()=>switchPanel(t.dataset.panel));
  $('#addCodeRow').onclick=()=>$('#codeBody').insertAdjacentHTML('beforeend',rowHtml([{name:'file_name',placeholder:'main.py'},{name:'language',placeholder:'python'},{name:'work_type',placeholder:'修改'},{name:'description',placeholder:'说明'}]));
  $('#addDocumentRow').onclick=()=>$('#documentBody').insertAdjacentHTML('beforeend',rowHtml([{name:'document_name',placeholder:'设计说明'},{name:'document_type',placeholder:'docx'},{name:'work_type',placeholder:'修改'},{name:'description',placeholder:'说明'}]));
  document.body.addEventListener('click',async e=>{if(e.target.classList.contains('remove-row'))e.target.closest('tr').remove();const b=e.target.closest('button');if(!b)return;try{if(b.dataset.downloadReport)await downloadFile(`/api/my/reports/${b.dataset.downloadReport}/download`,b.dataset.file||'report.docx');if(b.dataset.artifact)await downloadFile(`/api/artifacts/${b.dataset.artifact}/download`,b.dataset.file||'artifact.bin');if(b.dataset.editReport)await startReportEdit(b.dataset.editReport);if(b.dataset.viewTask){await refreshResults(b.dataset.viewTask,b.dataset.taskName);switchPanel('manager');$('#selectedTaskLabel').scrollIntoView({behavior:'smooth',block:'start'})}if(b.dataset.xlsxTask)await downloadFile(`/api/tasks/${b.dataset.xlsxTask}/export.xlsx`,'review_cases.xlsx');if(b.dataset.missingTask)await downloadFile(`/api/tasks/${b.dataset.missingTask}/missing-reports.xlsx`,'missing_reports.xlsx');if(b.dataset.docxTask)await downloadFile(`/api/tasks/${b.dataset.docxTask}/export.docx`,'review_cases.docx');if(b.dataset.deleteTask){await requestJson(`/api/tasks/${b.dataset.deleteTask}`,{method:'DELETE'});await Promise.all([refreshTasks(),refreshTaskHistory(),refreshStatus()])}if(b.dataset.downloadSnapshot)await downloadFile(`/api/testcase-snapshots/${b.dataset.downloadSnapshot}/download`,b.dataset.file||'snapshot.xlsx')}catch(err){alert(err.message)}});
  $('#resetForm').onclick=resetReportForm;$('#cancelReportEdit').onclick=resetReportForm;
  $('#reportForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,editing=state.editingReportId;$('#formMessage').textContent=editing?'保存更改中...':'提交中...';try{const payload=Object.fromEntries(new FormData(form).entries());payload.code_items=collectRows('#codeBody');payload.document_items=collectRows('#documentBody');payload.testcase_items=state.editingReportData?.testcase_items||[];const fd=new FormData();fd.append('payload',JSON.stringify(payload));Array.from($('#codeFiles').files).forEach(f=>fd.append('code_files',f));Array.from($('#documentFiles').files).forEach(f=>fd.append('document_files',f));Array.from($('#testcaseFiles').files||[]).forEach(f=>fd.append('testcase_files',f));const r=await requestForm(editing?`/api/my/reports/${encodeURIComponent(editing)}`:'/api/reports',fd,editing?'PUT':'POST');$('#formMessage').textContent=editing?'日报已更改。':`已生成 ${r.file}`;resetReportForm();await refreshMyReports()}catch(err){$('#formMessage').textContent=err.message}};
  $('#refreshMyReports').onclick=refreshMyReports;$('#exportWord').onclick=()=>downloadFile('/api/export/reports.docx?'+reportQuery(),'daily_reports.docx');
  $('#periodicExportForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,payload=Object.fromEntries(new FormData(form).entries()),format=e.submitter?.dataset.periodicFormat||'docx',message=$('#periodicExportMessage');if(!payload.start||!payload.end){message.textContent='请选择开始日期和结束日期';return}if(payload.start>payload.end){message.textContent='开始日期不能晚于结束日期';return}message.textContent='导出中...';try{await downloadFile(`/api/export/periodic.${format}?${new URLSearchParams(payload)}`,`${payload.report_type}_${payload.start}_${payload.end}.${format}`);message.textContent=`${format==='docx'?'Word':'Excel'} 已开始下载。`}catch(err){message.textContent=err.message}};
  $('#runCheck').onclick=async()=>{const startedAt=Date.now();setCheckProgress(true,'正在查重，请勿关闭或刷新页面…');try{const res=await requestJson('/api/run',{method:'POST',body:'{}'});setCheckProgress(true,checkCompletionMessage(res,startedAt));await Promise.all([refreshStatus(),refreshTasks(),refreshTaskHistory(),refreshResults()])}catch(err){setCheckProgress(false,`查重失败：${err.message}`);return}setCheckProgress(false,$('#taskMessage').textContent)};
  $('#taskForm').onsubmit=async e=>{e.preventDefault();const startedAt=Date.now();setCheckProgress(true,'正在查重，请勿关闭或刷新页面…');try{const payload=Object.fromEntries(new FormData(e.currentTarget).entries());const res=await requestJson('/api/tasks',{method:'POST',body:JSON.stringify(payload)});setCheckProgress(true,checkCompletionMessage(res,startedAt));await Promise.all([refreshStatus(),refreshTasks(),refreshTaskHistory(),refreshResults(res.task_id)])}catch(err){setCheckProgress(false,`查重失败：${err.message}`);return}setCheckProgress(false,$('#taskMessage').textContent)};
  $('#refreshTasks').onclick=refreshTasks;$('#refreshTaskHistory').onclick=refreshTaskHistory;$('#clearTaskDisplay').onclick=async()=>{await requestJson('/api/tasks/display/clear',{method:'POST',body:'{}'});await refreshTasks()};$('#searchBox').oninput=renderResults;$('#dateFilter').onchange=renderResults;$('#riskFilter').onchange=renderResults;
  $('#snapshotForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;try{const fd=new FormData(form),f=$('#snapshotFile').files[0];if(!f)throw new Error('请选择 Excel');fd.append('snapshot_file',f);if(state.user?.role==='group_leader'&&state.user.group_id)fd.set('group_id',state.user.group_id);const r=await requestForm('/api/testcase-snapshots',fd);$('#snapshotMessage').textContent=`上传成功：${r.snapshot_id}`;form.reset();renderSnapshotGroupOptions();await refreshSnapshots()}catch(err){$('#snapshotMessage').textContent=err.message}};$('#refreshSnapshots').onclick=refreshSnapshots;
  $('#userRole').innerHTML=roleOptions('employee');$('#userRole').onchange=applyUserFormRules;$('#userDepartment').onchange=()=>{updateAdminGroupOptions();applyUserFormRules()};
  $('#userForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const p=Object.fromEntries(new FormData(form).entries());if(['minister','admin'].includes(p.role)){p.department_id='';p.group_id=''}else if(p.role==='director')p.group_id='';setAdminMessage('#userMessage','新增中...');try{await requestJson('/api/users',{method:'POST',body:JSON.stringify(p)});form.reset();updateAdminGroupOptions();applyUserFormRules();await refreshUsers();setAdminMessage('#userMessage','账号已新增。')}catch(err){setAdminMessage('#userMessage',err.message)}};
  $('#departmentForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,payload=Object.fromEntries(new FormData(form).entries());setAdminMessage('#departmentMessage','新增中...');try{await requestJson('/api/departments',{method:'POST',body:JSON.stringify(payload)});form.reset();await refreshOrganisationAdmin();setAdminMessage('#departmentMessage','部门已新增并刷新显示。')}catch(err){setAdminMessage('#departmentMessage',err.message)}};
  $('#groupForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,payload=Object.fromEntries(new FormData(form).entries());setAdminMessage('#groupMessage','新增中...');try{await requestJson('/api/groups',{method:'POST',body:JSON.stringify(payload)});form.reset();await refreshOrganisationAdmin();setAdminMessage('#groupMessage','小组已新增并刷新显示。')}catch(err){setAdminMessage('#groupMessage',err.message)}};
  $('#settingsForm').onsubmit=async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget).entries()),payload={};for(const[k,v]of Object.entries(raw))payload[k]=v==='true'?true:v==='false'?false:(Number.isNaN(Number(v))?v:Number(v));await requestJson('/api/admin/settings',{method:'PUT',body:JSON.stringify(payload)});$('#settingsMessage').textContent='参数已保存';await refreshSettings()};
  $('#userList').onchange=e=>{const field=e.target.dataset.field,id=e.target.dataset.user;if(!id)return;const dept=$(`[data-user="${id}"][data-field="department_id"]`),group=$(`[data-user="${id}"][data-field="group_id"]`),role=$(`[data-user="${id}"][data-field="role"]`);if(field==='department_id')group.innerHTML=groupOptions('',dept.value,true);if(field==='role'&&['minister','admin'].includes(role.value)){dept.value='';group.innerHTML=groupOptions('', '',true);group.value=''}if(field==='role'&&role.value==='director')group.value=''};
  $('#userList').onclick=async e=>{const save=e.target.closest('[data-save-user]'),del=e.target.closest('[data-delete-user]');if(!save&&!del)return;try{if(save){const id=save.dataset.saveUser,p={};$$(`[data-user="${id}"]`).forEach(n=>p[n.dataset.field]=n.type==='checkbox'?n.checked:n.value);if(['minister','admin'].includes(p.role)){p.department_id='';p.group_id=''}else if(p.role==='director')p.group_id='';await requestJson(`/api/users/${id}`,{method:'PUT',body:JSON.stringify(p)});setAdminMessage('#userMessage','账号信息已保存。')}if(del){await requestJson(`/api/users/${del.dataset.deleteUser}`,{method:'DELETE'});setAdminMessage('#userMessage','账号已删除。')}await refreshUsers()}catch(err){setAdminMessage('#userMessage',err.message);await refreshUsers().catch(()=>{})}};
  $('#departmentList').onclick=async e=>{const save=e.target.closest('[data-save-dept]'),del=e.target.closest('[data-delete-dept]');if(!save&&!del)return;try{if(save){const id=save.dataset.saveDept,p={};$$(`[data-dept="${id}"]`).forEach(n=>p[n.dataset.field]=n.type==='checkbox'?n.checked:n.value);await requestJson(`/api/departments/${id}`,{method:'PUT',body:JSON.stringify(p)});setAdminMessage('#departmentMessage','部门已保存。')}if(del){const id=del.dataset.deleteDept;if(!confirm('确定删除该部门吗？部门下的小组和人员需先迁移或删除。'))return;await requestJson(`/api/departments/${id}`,{method:'DELETE'});setAdminMessage('#departmentMessage','部门已删除。')}await refreshOrganisationAdmin()}catch(err){setAdminMessage('#departmentMessage',err.message)}};
  $('#groupList').onclick=async e=>{const save=e.target.closest('[data-save-group]'),del=e.target.closest('[data-delete-group]');if(!save&&!del)return;try{if(save){const id=save.dataset.saveGroup,p={};$$(`[data-group="${id}"]`).forEach(n=>p[n.dataset.field]=n.type==='checkbox'?n.checked:n.value);await requestJson(`/api/groups/${id}`,{method:'PUT',body:JSON.stringify(p)});setAdminMessage('#groupMessage','小组已保存。')}if(del){const id=del.dataset.deleteGroup;if(!confirm('确定删除该小组吗？小组内人员需先迁移或删除。'))return;await requestJson(`/api/groups/${id}`,{method:'DELETE'});setAdminMessage('#groupMessage','小组已删除。')}await refreshOrganisationAdmin()}catch(err){setAdminMessage('#groupMessage',err.message)}};
  $('#testLlm').onclick=async()=>{$('#systemMessage').textContent='测试中...';try{$('#systemMessage').textContent=JSON.stringify(await requestJson('/api/admin/test-llm',{method:'POST',body:'{}'}))}catch(e){$('#systemMessage').textContent=e.message}};$('#cleanupSessions').onclick=async()=>{$('#systemMessage').textContent=JSON.stringify(await requestJson('/api/admin/cleanup-sessions',{method:'POST',body:'{}'}))};$('#storageStats').onclick=async()=>{$('#systemMessage').textContent=JSON.stringify(await requestJson('/api/admin/storage-stats'))};$('#backupStorage').onclick=async()=>{$('#systemMessage').textContent=JSON.stringify(await requestJson('/api/admin/backup',{method:'POST',body:'{}'}))};
  $('#resetBusinessData').onclick=async()=>{if(!confirm('此操作会清除全部业务数据和文件，但保留账号、部门、小组和系统参数。是否继续？'))return;try{const prep=await requestJson('/api/admin/reset/prepare',{method:'POST',body:'{}'}),phrase=prompt(`再次确认：请输入“${prep.confirmation_phrase}”`);if(phrase!==prep.confirmation_phrase){$('#resetMessage').textContent='确认文字不匹配，已取消';return}const result=await requestJson('/api/admin/reset/confirm',{method:'POST',body:JSON.stringify({confirmation_id:prep.confirmation_id,confirmation_phrase:phrase})});alert(`清理完成，共移除 ${result.removed_files} 个文件。请重新登录。`);location.reload()}catch(err){$('#resetMessage').textContent=err.message}};
}
bindEvents();refreshAuth().catch(()=>applyRoleUi());
