from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from src.core.schemas import Report, User


class DatabaseBackend(ABC):
    """Replace the implementation when moving from SQLite to PostgreSQL/MySQL."""

    @abstractmethod
    def initialize(self, seed_demo_users: bool = True) -> None: ...
    @abstractmethod
    def authenticate(self, username: str, password: str) -> User | None: ...
    @abstractmethod
    def create_session(self, user_id: str, days: int = 7) -> str: ...
    @abstractmethod
    def delete_session(self, session_id: str) -> None: ...
    @abstractmethod
    def cleanup_sessions(self) -> int: ...
    @abstractmethod
    def user_by_session(self, session_id: str) -> User | None: ...
    @abstractmethod
    def list_departments(self, public_only: bool = False) -> list[dict[str, Any]]: ...
    @abstractmethod
    def create_department(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def update_department(self, department_id: str, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    def delete_department(self, department_id: str) -> None: ...
    @abstractmethod
    def list_groups(self, department_id: str = "", public_only: bool = False) -> list[dict[str, Any]]: ...
    @abstractmethod
    def create_group(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def update_group(self, group_id: str, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    def delete_group(self, group_id: str) -> None: ...
    @abstractmethod
    def list_users(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    def list_required_submitters(self, user: User | None) -> list[dict[str, Any]]: ...
    @abstractmethod
    def list_export_submitters(self, user: User) -> list[dict[str, Any]]: ...
    @abstractmethod
    def create_user(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def update_user(self, user_id: str, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    def reset_user_password(self, user_id: str, password: str) -> None: ...
    @abstractmethod
    def delete_user(self, user_id: str) -> None: ...
    @abstractmethod
    def save_artifact(self, payload: dict[str, Any]) -> str: ...
    @abstractmethod
    def list_artifacts_for_report(self, report_id: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    def get_artifact(self, artifact_id: str, user: User | None = None) -> dict[str, Any] | None: ...
    @abstractmethod
    def save_report(self, report: Report) -> str: ...
    @abstractmethod
    def list_reports(self, user: User | None = None, start: str = "", end: str = "", include_withdrawn: bool = False, name: str = "", role: str = "") -> list[Report]: ...
    @abstractmethod
    def get_report(self, report_id: str, user: User | None = None) -> Report | None: ...
    @abstractmethod
    def update_report_status(self, report_id: str, status: str, user: User, revision_of_report_id: str = "") -> None: ...
    @abstractmethod
    def lock_reports_for_task(self, task_id: str, report_ids: list[str]) -> None: ...
    @abstractmethod
    def save_testcase_snapshot(self, payload: dict[str, Any]) -> str: ...
    @abstractmethod
    def list_testcase_snapshots(self, user: User) -> list[dict[str, Any]]: ...
    @abstractmethod
    def get_testcase_snapshot(self, snapshot_id: str, user: User | None = None) -> dict[str, Any] | None: ...
    @abstractmethod
    def find_testcase_snapshot(self, group_id: str, report_date: str) -> dict[str, Any] | None: ...
    @abstractmethod
    def find_latest_testcase_snapshot_before(self, group_id: str, report_date: str) -> dict[str, Any] | None: ...
    @abstractmethod
    def create_task(self, user: User, payload: dict[str, Any], config_snapshot: dict[str, Any], result_dir: str) -> str: ...
    @abstractmethod
    def begin_automatic_task(self, report_date: str, payload: dict[str, Any], config_snapshot: dict[str, Any], result_dir: str) -> tuple[str, bool]: ...
    @abstractmethod
    def finish_task(self, task_id: str, status: str, result: dict[str, Any], error: str = "", failure_type: str = "", attempt_no: int | None = None) -> bool: ...
    @abstractmethod
    def list_tasks(self, user: User, filters: dict[str, Any] | None = None, include_hidden: bool = True) -> list[dict[str, Any]]: ...
    @abstractmethod
    def get_task(self, task_id: str, user: User | None = None) -> dict[str, Any] | None: ...
    @abstractmethod
    def get_task_status(self, task_id: str, user: User | None = None) -> dict[str, Any] | None: ...
    @abstractmethod
    def list_admin_tasks(self, filters: dict[str, Any] | None = None, cursor: str = "", limit: int = 50) -> dict[str, Any]: ...
    @abstractmethod
    def get_worker_lease(self) -> dict[str, Any] | None: ...
    @abstractmethod
    def start_llm_call(self, call_id: str, task_id: str, started_at: str) -> None: ...
    @abstractmethod
    def finish_llm_call(self, call_id: str, finished_at: str, duration_ms: int, ok: bool, error_type: str = "") -> None: ...
    @abstractmethod
    def resource_monitor_summary(self, retention_days: int = 7) -> dict[str, Any]: ...
    @abstractmethod
    def admin_pause_task(self, task_id: str) -> str: ...
    @abstractmethod
    def admin_resume_task(self, task_id: str) -> str: ...
    @abstractmethod
    def admin_restart_task(self, task_id: str) -> str: ...
    @abstractmethod
    def admin_force_terminate_task(self, task_id: str) -> str: ...
    @abstractmethod
    def delete_task(self, task_id: str, user: User) -> str: ...
    @abstractmethod
    def complete_task_deletion(self, task_id: str, attempt_no: int) -> bool: ...
    @abstractmethod
    def reap_task_deletions(self, stale_before: str) -> list[str]: ...
    @abstractmethod
    def clear_task_page_display(self, user: User) -> None: ...
    @abstractmethod
    def create_reset_confirmation(self, user_id: str) -> str: ...
    @abstractmethod
    def consume_reset_confirmation(self, confirmation_id: str, user_id: str) -> bool: ...
    @abstractmethod
    def clear_business_data(self) -> dict[str, int]: ...
    @abstractmethod
    def save_export(self, payload: dict[str, Any]) -> str: ...
    @abstractmethod
    def get_settings(self, defaults: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def update_settings(self, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    def append_audit_log(self, payload: dict[str, Any]) -> str: ...
    @abstractmethod
    def list_audit_logs(self, filters: dict[str, Any], cursor: str = "", limit: int = 50) -> dict[str, Any]: ...
    @abstractmethod
    def export_audit_logs(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def append_runtime_log(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def list_runtime_logs(self, filters: dict[str, Any], cursor: str = "", limit: int = 100) -> dict[str, Any]: ...
    @abstractmethod
    def stream_runtime_logs(self, filters: dict[str, Any], after_seq: int = 0, limit: int = 100) -> list[dict[str, Any]]: ...
